# Exclude all 3rd-party libraries
exclude: |
  (?x)^(
    third_party/.+
  )$
repos:
  # Common hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.5
    hooks:
      - id: remove-crlf
      - id: remove-tabs
        name: Tabs remover (C++)
        files: \.(c|cc|cxx|cpp|cu|h|cuh|hpp|hxx|xpu|kps)$
        args: [--whitespaces-count, '2']
      - id: remove-tabs
        name: Tabs remover (Python)
        files: (.*\.py)$
        args: [--whitespaces-count, '4']
      - id: insert-license  # Insert a short license disclaimer as a header comment in Python files
        name: License inserter (Python)
        files: \.py$
        args:
          - --license-filepath
          - LICENSE
          - --comment-style
          - "#"
          - --use-current-year
          - --no-extra-eol
      - id: insert-license  # Insert a short license disclaimer as a header comment in C++ files
        name: License inserter (C++)
        files: \.(c|cc|cxx|cpp|cu|h|cuh|hpp|hxx|xpu|kps)$
        args:
          - --license-filepath
          - LICENSE
          - --comment-style
          - "//"
          - --use-current-year
          - --no-extra-eol
  - repo: https://github.com/PFCCLab/typos-pre-commit-mirror.git
    rev: v1.35.1
    hooks:
      - id: typos
        args: [--force-exclude]
  # For Python files
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --no-cache]
  # For C++ files
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        description: Format files with ClangFormat.
        entry: bash ./tools/codestyle/clang_format.sh -i
        language: system
        files: \.(c|cc|cxx|cpp|cu|h|cuh|hpp|hxx|xpu|kps)$
  - repo: local
    hooks:
      - id: cpplint-cpp-source
        name: cpplint
        description: Check C++ code style using cpplint.py.
        entry: bash ./tools/codestyle/cpplint.sh
        language: system
        files: \.(cc|cxx|cpp|cu|h|hpp|hxx)$
        args:
          - --extensions=cc,cxx,cpp,cu,cuh,h,hpp,hxx,kps
          - --filter=-readability/fn_size,-build/include_what_you_use,-build/c++11,-whitespace/parens,-whitespace/indent_namespace
          - --quiet
  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        description: Parallel clang-tidy runner.
        entry: python ./tools/codestyle/clang-tidy.py
        language: system
        files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
        args:
          - -p=build/
          - -extra-arg=-Wno-unknown-warning-option
          - -extra-arg=-Wno-pessimizing-move
          - -extra-arg=-Wno-braced-scalar-init
          - -extra-arg=-Wno-dangling-gsl
          - -extra-arg=-Wno-deprecated-copy
          - -extra-arg=-Wno-final-dtor-non-final-class
          - -extra-arg=-Wno-implicit-int-float-conversion
          - -extra-arg=-Wno-inconsistent-missing-override
          - -extra-arg=-Wno-infinite-recursion
          - -extra-arg=-Wno-mismatched-tags
          - -extra-arg=-Wno-self-assign
          - -extra-arg=-Wno-sign-compare
          - -extra-arg=-Wno-sometimes-uninitialized
          - -extra-arg=-Wno-tautological-overlap-compare
          - -extra-arg=-Wno-unused-const-variable
          - -extra-arg=-Wno-unused-lambda-capture
          - -extra-arg=-Wno-unused-private-field
          - -extra-arg=-Wno-unused-value
          - -extra-arg=-Wno-unused-variable
          - -extra-arg=-Wno-overloaded-virtual
          - -extra-arg=-Wno-defaulted-function-deleted
          - -extra-arg=-Wno-delete-non-abstract-non-virtual-dtor
          - -extra-arg=-Wno-return-type-c-linkage
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
  - repo: https://github.com/PFCCLab/cmake-lint-paddle
    rev: v1.5.2
    hooks:
      - id: cmakelint
        args: [--config=./tools/codestyle/.cmakelintrc]
