FROM rocm/pytorch:rocm7.1.1_ubuntu22.04_py3.10_pytorch_release_2.10.0

RUN apt-get update && \
    apt-get install -y \
    git \
    cython3 \
    ibverbs-utils \
    openmpi-bin \
    libopenmpi-dev \
    libpci-dev \
    cmake \
    libdw1 \
    locales && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    amd-aiter ninja prettytable pytest-assume \
    setuptools-scm cmake 'setuptools>=65'

COPY . /workspace/mori
WORKDIR /workspace/mori

ARG MORI_GPU_ARCHS=gfx950
ENV SETUPTOOLS_SCM_PRETEND_VERSION=0.1.0
RUN MORI_GPU_ARCHS=${MORI_GPU_ARCHS} \
    PYTORCH_ROCM_ARCH=${MORI_GPU_ARCHS} \
    pip3 install . --no-cache-dir --no-build-isolation

ENV PYTHONPATH=/workspace/mori:${PYTHONPATH}
ENV HSA_NO_SCRATCH_RECLAIM=1
ENV PATH=/root/.local/bin:${PATH}

CMD ["/bin/bash"]
